server:
  port: 1111
spring:
  application:
    name: zwl-eureka
  #由于该应用是注册中心，false：代表不向注册中心注册自己;true:代表注册自己
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    #是否启动检测服务，由于注册中心的职责是维护服务实例，所以它不需要检服务
    fetch-registry: false
    service-url.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
